config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope ENV['RAILS_RELATIVE_URL_ROOT'] || '/' do
    get '/auth/create', to: 'sessions#create', as: 'auth_create'
    get '/auth/logout', to: 'sessions#destroy', as: 'auth_logout'

    resources :collections
    resources :closed_hours
    resources :open_hours
    resources :tags

    resources :settings do
      collection do
        put :update
        patch :update
      end
    end

    get '/invaliduser', to: 'pages#invaliduser', as: 'invalid_user'
    get '/selfserve', to: 'bookings#self_serve', as: 'selfserve'
    get '/selfserve_disabled', to: 'pages#selfserve_disabled', as: 'selfserve_disabled'
    get '/selfserve_success', to: 'pages#selfserve_success', as: 'selfserve_success'
    get '/selfserve_fail', to: 'pages#selfserve_fail', as: 'selfserve_fail'
    get '/approvals', to: 'bookings#approvals', as: 'approvals'
    get '/bookings/:id/reject', to: 'bookings#reject', as: 'reject', defaults: { format: :json }
    get '/bookings/:id/approve', to: 'bookings#approve', as: 'approve', defaults: { format: :json }
    post '/bookings/:id/scan', to: 'bookings#scan', as: 'scan', defaults: { format: :json }
    get '/user_history', to: 'pages#user_history', as: 'user_history'
    get '/equipment/download', to: 'equipment#download_excel'
    get '/equipment/unavailable', to: 'equipment#unavailable_time_range', defaults: { format: :json }
    get '/equipment/:id/summary_view', to: 'equipment#summary_view', as: 'equipment_summary_view'
    get '/tags/form/:tagid', to: 'tags#form', as: 'tag_form' # generate a partial to edit existing forms
    get '/users/form/:userid', to: 'users#form', as: 'user_form' # generate a partial to edit existing forms
    get '/equipment/form/:equip_id', to: 'equipment#form', as: 'equipment_form' # generate a partial to edit existing forms
    get '/bookings/:id/self_serve', to: 'bookings#self_serve', as: 'selfserve_edit'
    get '/bookings/equiprow/:equip_id', to: 'bookings#equipment_row', as: 'equiprow' # generate the partial js for a bookings row
    get '/bookings/overdue', to: 'bookings#overdue', defaults: { format: :json }
    get '/bookings/upcoming', to: 'bookings#upcoming', defaults: { format: :json }
    get '/bookings/upcoming_returns', to: 'bookings#upcoming_returns', defaults: { format: :json }
    get '/bookings/calendar', to: 'pages#calendar_new'
    get '/bookings/approvals', to: 'bookings#approvals', defaults: { format: :json }
    get '/users/validate_dept/:userid.json', to: 'users#validate_dept', defaults: { format: :json } # get whether a user is from a valid department
    get '/users/ldap/:userid.json', to: 'users#ldap', defaults: { format: :json } # get LDAP details for a user
    get '/users/ldap_user/:username.json', to: 'users#valid_ldap_user', defaults: { format: :json } # determine if a username exists in LDAP
    get '/users/:column.json', to: 'users#column', defaults: { format: :json }, constraints: ->(request) { User.column_names.include?(request.params[:column]) }
    get '/users/ldap_search/', to: 'users#ldap_search', defaults: { format: :json }
    get '/equipment/bytag/', to: 'equipment#tags', as: 'bytag'
    get '/equipment/:column.json', to: 'equipment#column', defaults: { format: :json }, constraints: ->(request) { Equipment.column_names.include?(request.params[:column]) }
    get '/hours_by_date', to: 'settings#hours_by_date', as: 'hours_by_date', defaults: { format: :json }
    get '/events/calendar', to: 'events#calendar', defaults: { format: :json }
    get '/equipment/:id/future_events', to: 'equipment#future_events', defaults: { format: :json }

    resources :equipment
    resources :users
    resources :bookings
    resources :events

    root to: 'pages#home2'
  end
end

app/models/user.rb
# frozen_string_literal: true

require 'json'
require 'net/ldap'
# Users serve two purposes in the application. They are the admins managing
# bookings and other content, and they are the people who are reserving
# equipment for their use. Those with the ability to manage all bookings are
# classified as admins (User.admin == true). Those who are simply "clients"
# are not (User.admin == false).
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable
  # devise :cas_authenticatable
  # include HTTParty

  before_save :default_values
  has_many :bookings
  has_many :approved_by, class_name: 'Booking', inverse_of: :approver
  accepts_nested_attributes_for :bookings
  validates :username, uniqueness: true
  validates :username, presence: true

  @@valid_statuses = [['Good Standing', 0], ['Warned', 1], ['Blacklisted', 2]]

  def self.find_or_create_from_username(username)
    u = User.find_by_username(username)
    u = User.create(username: username) if u.nil?
    u
  end

  def self.admin_user?(uname)
    admin_user = false

    unless User.where(username: uname).empty?
      admin_user = !User.where(username: uname, admin: true).empty?
    end

    admin_user
  end

  def default_values
    self.admin = false if admin.nil?
    self.status = 0 if status.nil?
  end

  # Is the user from a valid department?

  # getter for the valid_statuses array
  def self.valid_statuses
    @@valid_statuses
  end

  # returns the status string by the status number
  def self.get_status(status_id)
    @@valid_statuses.each do |status|
      return status[0] if status[1] == status_id
    end

    'Invalid Status'
  end


  def self.ldap_search(username_part)
    # Create ldap connection
    ldap = Net::LDAP.new(
      host: 'uwldap.uwaterloo.ca',
      base: 'dc=uwaterloo,dc=ca'
    )

    # Search for username
    search_result = ldap.search(filter: Net::LDAP::Filter.construct("
      (&(&(ou=*)(!(ou=Unknown)))(uid=#{username_part}*))"))

    if search_result.nil?
      {}
    else
      search_result
    end
  end

  # TODO: Replace with LDAP query
  # returns whether a username is a known LDAP user
  def self.ldap_user?(username)
    collection = Collection.first
    # validate WatIAM by default, unless setting exists and is set to 0
    return true if collection.settings(:validation).watiam == '0'

    # Look for user in LDAP. If there is only one match for the username, and
    # it is an exact match for the UID in LDAP, return true
    if ldap_search(username).length == 1 && ldap_search(username)[0][:uid][0]
      return true 
    else
      # Not a valid LDAP user    
      return false
    end
  end

  def ldap_details
    # Create ldap connection
    ldap = Net::LDAP.new(
      host: 'uwldap.uwaterloo.ca',
      base: 'dc=uwaterloo,dc=ca'
    )

    # Search for username
    search_result = ldap.search(filter: Net::LDAP::Filter.eq('uid', username))

    if search_result.nil?
      {}
    else
      search_result.first
    end
  end

  # return true if the user is from a valid department (as set in Settings)
  # or false otherwise
  def validate_department
    collection = Collection.first
    ldap_response = User.ldap_search(username)
    if ldap_response.length == 1 && ldap_response[0][:uid][0]
      dept = ldap_response[0][:ou]
    end

    valid_depts = collection.settings(:validation).departments
    valid_depts_list =  if valid_depts.nil? or valid_depts.empty?
                          []
                        else
                          valid_depts.split('|').map(&:strip)
                        end
    # check for intersection between valid_depts_list and dept
    common_ou = valid_depts_list & dept
    if common_ou.length.positive?
      true
    else
      false
    end
  end

  # returns the user's email address from UW LDAP
  def email_address
    ldap_response = User.ldap_search(username)
    if ldap_response.length == 1 && ldap_response[0][:uid][0]
      # email = ldap_response[0][:mail]
      uid = ldap_response[0]["uid"][0]
      email = "#{uid}@uwaterloo.ca"
      return email
    else
      return nil
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true
require 'will_paginate/array'
# UsersController manages CRUD operations for Users
class UsersController < ApplicationController
  # before_action :authenticate_user! do |controller|
  #   controller.admin_user()
  # end

  before_action :authenticate
  before_action :authenticate_admin, except: %i[show]

  def form
    @user_id = params[:userid]

    @user = @user_id.nil? || /^[0-9]+$/.match(@user_id).nil? ? User.new : User.find(@user_id)

    respond_to do |format|
      format.js
    end
  end

  def validate_dept
    @user = User.find_by(username: params[:userid])
    respond_to do |format|
      format.json { render json: @user.validate_department }
    end
  end

  def ldap
    @user = User.find_by(username: params[:userid])
    @details = if @user.nil?
                 nil
               else
                 @user.ldap_details
               end

    respond_to do |format|
      format.json { render json: @details }
    end
  end

  def valid_ldap_user
    valid = User.ldap_user?(params[:username])

    respond_to do |format|
      format.json { render json: valid }
    end
  end

  def column
    if request.params[:term]
      @users = User.where('username LIKE ?', '%' + request.params[:term] + '%').pluck(request.params[:column])
    else
      @users = User.pluck(request.params[:column])
    end
    respond_to do |format|
      format.json { render json: @users }
    end
  end

  def ldap_search
    users = if request.params[:username]
              User.ldap_search(request.params[:username])
            else
              []
            end
    respond_to do |format|
      # format.json { render json: users }
      format.json do
        render json: users.map { |user|
                       u = User.find_by_username(user[:uid].first)
                       status = u.nil? ? 0 : u.status
                       comments = u.nil? ? '' : u.comments
                       id = u.nil? ? -1 : u.id
                       {
                         username: user[:uid].first,
                         ou: user[:ou].join(','),
                         status: status,
                         comments: comments,
                         user_id: id
                       }
                     }
      end
    end
  end

  # GET /users
  # GET /users.json
  def index
    page_size = 10
    if params[:per_page].present?
      page_size = params[:per_page] == 'all' ? 0 : params[:per_page].to_i
    end
    if request.params[:sort_order]
      sort_order = request.params[:sort_order]
    else
      sort_order = "ASC"
    end
    @users = if request.params[:search]
               User.where('username LIKE ?', "%#{request.params[:search]}%").order("username #{sort_order}").paginate(page: params[:page], per_page: page_size)
             else
               User.all.order("username #{sort_order}").paginate(page: params[:page], per_page: page_size)
             end


    respond_to do |format|
      format.html # index.html.erb
      if @users.count > 10
        format.json { render json: @users }
      else
        format.json { render json: @users.map { |user| user.attributes.merge(ldap_details: user.ldap_details) } }
      end
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    logged_in_user = User.find_by_username(session[:current_username])

    respond_to do |format|
      if (logged_in_user.admin)
        # Admins can see information about anyone
        format.html # show.html.erb
        format.json { render json: @user }
      else
        # Non-admin users should only be able to get information about themselves
        if (@user.username == logged_in_user.username)
          format.html # show.html.erb
          format.json { render json: @user }
        else
          format.html # show.html.erb
          format.json { render json: {}, status: 401 }
        end
      end
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    up = user_params
    up[:username] = up[:username].strip
    @user = User.new(up)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    up = user_params
    up[:username] = up[:username].strip
    
    respond_to do |format|
      if @user.update(up)
        format.html { redirect_to root_path, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :admin, :status, :comments, :firstname, :lastname)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# UsersHelper does nothing
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class="row">
    <div class="col">

      <div class="mb-3">
        <label for="username">Username</label>
        <%= f.text_field :username, 
          :class => 'form-control',
          :placeholder => 'Enter a WatIAM Username',
          :id => 'username'
        %>
      </div>

      <div class="mb-3">
        <label for="first_name">First Name</label>
        <%= f.text_field :firstname, 
          :class => 'form-control',
          :id => 'first_name'
        %>
      </div>

      <div class="mb-3">
        <label for="last_name">Last Name</label>
        <%= f.text_field :lastname, 
          :class => 'form-control',
          :id => 'last_name'
        %>
      </div>

      <div class="mb-3">
        <label for="comments">Comments</label>
        <%= f.text_area :comments, 
          :class => 'form-control',
          :id => 'comments'
        %>
      </div>

      <div class="mb-3">
        <label for="admin">Admin?</label>
        <%= f.select :admin, 
          {"No" => false, "Yes" => true},
          :id => "admin"
        %>
      </div>

      <div class="mb-3">
        <label for="status">Status</label>
        <%= f.select :status, 
          options_for_select(User.valid_statuses, @user.status),
          :id => "status"
        %>
      </div>


    </div>
  </div>

    <!-- button row -->
  <div class="row">
    <div class="col">
      <% if @user.new_record? %>
        <%= button_tag(type: 'submit', id: "submituser", class: "btn btn-primary") do %>
          Create
        <% end %>
        <%= link_to 'Cancel', users_path, method: :get, class: "btn btn-secondary" %>
      <% else %>
        <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
          Update
        <% end %>
        <%= link_to 'Delete', @user, confirm: 'Are you sure? This cannot be undone.', method: :delete, :class => 'btn btn-danger' %>
        <%= link_to 'Cancel', @user, method: :get, class: "btn btn-secondary" %>
      <% end %>
    </div>
  </div>
      
<% end %>

app/views/users/_list.html.erb
<ul class="list users">
  <% User.all.sort{|a,b| a.username <=> b.username}.each do |user| %>
    <li>
    	<% if user.status == 0 %>
    		<i class="status right fas fa-circle good"></i>
    	<% else %>
    		<i class="status right fas fa-circle bad"></i>
    	<% end %>
        <span class="name"><%= link_to user.username,"javascript:createUserForm(" + user.id.to_s + ");" %></span>
    </li>
  <% end %>
</ul>

app/views/users/edit.html.erb
<div>
	<div class="row">
		<div class="col mt-2">
			<h3>Editing user <%= @user.username %></h3>
		</div>
	</div>
	<%= render 'form' %>
</div>

app/views/users/form.js.erb
var form_data = "<%= j render partial: 'users/form', locals: {user_id: @user_id} %>";

$('.add-users').html(form_data);

//initalize the clear button
$('.booking-clear').click(function() {
	$('.add-users').hide();
	$('.logout-button').show();
});

app/views/users/index.html.erb
<%= vite_client_tag %>
<%= vite_javascript_tag "user_list" %>
<main id="user_list">
  
  <h2>User List</h2>

  <!-- filters -->
  <div class="row equipment-toolbar">
    <div class="col">
      <form action="./users" method="get">
        <div class="btn-toolbar" role="toolbar">
          <div class="input-group me-2">
            <%= text_field_tag "search", params[:search], class: "form-control me-2", id: "search_all", placeholder: "username" %>
          </div>

          <%= label_tag(:sort_order, "Sort", class: "sr-only") %>
          <div class="input-group me-2">
            <div class="input-group-prepend">
              <div class="input-group-text">Sort</div>
            </div>
            <%= select_tag(
              :sort_order,
              options_for_select(
                [
                  ["Username: A-Z", "ASC" ],
                  ["Username: Z-A", "DESC" ],
                ],
                params[:sort_order]
              ),
              class: "form-select"
            ) %>
          </div>

          <button class="btn btn-primary me-2" type="submit" id="applySearchFilters">
            Search
          </button>

          <button class="btn btn-secondary me-2" id="clearSearchFilters" >
            Clear
          </button>
        </div>
      </form>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col">
      <ul class="list-group">
        <% @users.each do |user| %>
          <li class="list-group-item">
            <div class="row">
              <div class="col-3">
                <%= user.username %>
              </div>
              <div class="col-6">
                First Name: <%= user.firstname %><br />
                Last Name: <%= user.lastname %><br />
                Status: <%= user.status %><br />
                Admin: <%= user.admin %><br />
                Comments: <%= user.comments %>
              </div>
              <div class="col-3">
                <span class="btn-group">
                  <%= button_to user, method: :get, class: "btn btn-outline-secondary"   do %>
                    <i class="fas fa-eye"></i>
                  <% end %>
                  <%= button_to edit_user_path(user), method: :get, class: "btn btn-outline-secondary"  do %>
                    <i class="fas fa-edit"></i>
                  <% end %>
                  <%= button_to user, confirm: 'Are you sure?', method: :delete, class: "btn btn-outline-secondary" do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                </span>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="row">
    <div class="flickr_pagination">
      <%= will_paginate @users %>
    </div>
  </div>
</main>

app/views/users/new.html.erb
<div>
<div class="row">
	<div class="col mt-2">
		<h3>Create user</h3>
	</div>
</div>
		<%= render 'form' %>

</div>

app/views/users/show.html.erb
<div class="row mt-3">
  <div class="col">
    <div class="card">
      <div class="card-header">User Details</div>
      <div class="card-body">
        <p>
          <b>Username:</b>
          <%= @user.username %>
        </p>

        <p>
          <b>Admin:</b>
          <%= @user.admin %>
        </p>

        <p>
          <b>Status:</b>
          <%= @user.status %>
        </p>
      </div>
      <div class="card-footer">
        <%= link_to 'Edit', edit_user_path(@user) %> |
        <%= link_to 'Back to Users List', users_path %>
      </div>
    </div>
  </div>

  <div class="col">
    <div class="card">
      <div class="card-header">
        Booking History
      </div>
      <div class="card-body">
        <%= link_to 'Sort Oldest First', user_path(@user, sort_direction: :sd_on) %>
        <%= link_to 'Sort Newest First', user_path(@user, sort_direction: :sd_no) %>
        <div class="history list-group">
          <%# Handle sort %>
          <% if params[:sort_direction] == "sd_on"
            bookings = @user.bookings.joins(:events).merge(Event.order(start: :asc)).limit(10)
          else
            bookings = @user.bookings.joins(:events).merge(Event.order(start: :desc)).limit(10)
          end %>
          <% bookings.each do |booking| %>
          <%= render partial: 'bookings/summary_row', locals: {booking: booking, view: 'admin'} %></li>
          <% end %>

          <%# If more than 10 items, show a link to bookings list %>

          <% if @user.bookings.joins(:events).merge(Event.order(start: :asc)).count > 10 %>
            <%= link_to "Show all bookings for #{@user.username}", bookings_path({user_search: @user.username, sort_order: params[:sort_direction]}) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- history -->