config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope ENV['RAILS_RELATIVE_URL_ROOT'] || '/' do
    get '/auth/create', to: 'sessions#create', as: 'auth_create'
    get '/auth/logout', to: 'sessions#destroy', as: 'auth_logout'

    resources :collections
    resources :closed_hours
    resources :open_hours
    resources :tags

    resources :settings do
      collection do
        put :update
        patch :update
      end
    end

    get '/invaliduser', to: 'pages#invaliduser', as: 'invalid_user'
    get '/selfserve', to: 'bookings#self_serve', as: 'selfserve'
    get '/selfserve_disabled', to: 'pages#selfserve_disabled', as: 'selfserve_disabled'
    get '/selfserve_success', to: 'pages#selfserve_success', as: 'selfserve_success'
    get '/selfserve_fail', to: 'pages#selfserve_fail', as: 'selfserve_fail'
    get '/approvals', to: 'bookings#approvals', as: 'approvals'
    get '/bookings/:id/reject', to: 'bookings#reject', as: 'reject', defaults: { format: :json }
    get '/bookings/:id/approve', to: 'bookings#approve', as: 'approve', defaults: { format: :json }
    post '/bookings/:id/scan', to: 'bookings#scan', as: 'scan', defaults: { format: :json }
    get '/user_history', to: 'pages#user_history', as: 'user_history'
    get '/equipment/download', to: 'equipment#download_excel'
    get '/equipment/unavailable', to: 'equipment#unavailable_time_range', defaults: { format: :json }
    get '/equipment/:id/summary_view', to: 'equipment#summary_view', as: 'equipment_summary_view'
    get '/tags/form/:tagid', to: 'tags#form', as: 'tag_form' # generate a partial to edit existing forms
    get '/users/form/:userid', to: 'users#form', as: 'user_form' # generate a partial to edit existing forms
    get '/equipment/form/:equip_id', to: 'equipment#form', as: 'equipment_form' # generate a partial to edit existing forms
    get '/bookings/:id/self_serve', to: 'bookings#self_serve', as: 'selfserve_edit'
    get '/bookings/equiprow/:equip_id', to: 'bookings#equipment_row', as: 'equiprow' # generate the partial js for a bookings row
    get '/bookings/overdue', to: 'bookings#overdue', defaults: { format: :json }
    get '/bookings/upcoming', to: 'bookings#upcoming', defaults: { format: :json }
    get '/bookings/upcoming_returns', to: 'bookings#upcoming_returns', defaults: { format: :json }
    get '/bookings/calendar', to: 'pages#calendar_new'
    get '/bookings/approvals', to: 'bookings#approvals', defaults: { format: :json }
    get '/users/validate_dept/:userid.json', to: 'users#validate_dept', defaults: { format: :json } # get whether a user is from a valid department
    get '/users/ldap/:userid.json', to: 'users#ldap', defaults: { format: :json } # get LDAP details for a user
    get '/users/ldap_user/:username.json', to: 'users#valid_ldap_user', defaults: { format: :json } # determine if a username exists in LDAP
    get '/users/:column.json', to: 'users#column', defaults: { format: :json }, constraints: ->(request) { User.column_names.include?(request.params[:column]) }
    get '/users/ldap_search/', to: 'users#ldap_search', defaults: { format: :json }
    get '/equipment/bytag/', to: 'equipment#tags', as: 'bytag'
    get '/equipment/:column.json', to: 'equipment#column', defaults: { format: :json }, constraints: ->(request) { Equipment.column_names.include?(request.params[:column]) }
    get '/hours_by_date', to: 'settings#hours_by_date', as: 'hours_by_date', defaults: { format: :json }
    get '/events/calendar', to: 'events#calendar', defaults: { format: :json }
    get '/equipment/:id/future_events', to: 'equipment#future_events', defaults: { format: :json }

    resources :equipment
    resources :users
    resources :bookings
    resources :events

    root to: 'pages#home2'
  end
end

app/views/shared/_booking_filter.html.erb
<div class="row">
  <div  class="col-6">
    <div id="tag_selector">
      <tag-selector></tag-selector>
    </div>
  </div>

  <div class="col-6">
    Select user: <input list="users" id="user_input" class="form-control">

    <datalist id="users">
      <option v-for="user in user_list" v-bind:value="user.username">
    </datalist>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="header row">
	<div class="large-6 small-12 columns">
		<h1>MAD Equipment</h1>
	</div>
</div>

app/views/shared/_legend.html.erb
<div id="legend">
	<div class="small-3 columns" style="background:#9933cc">Upcoming</div>
	<div class="small-3 columns" style="background:#3366ff">Active</div>
	<div class="small-3 columns" style="background:#00aa22">Finished</div>
	<div class="small-3 columns" style="background:#dd0000">Overdue</div>
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><%= Collection.first.settings(:collection).name %></a>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <i class="fas fa-sign-out-alt" style="color: white"></i>
          <%= link_to "Log out #{ session[:current_username]}", auth_logout_url, style: "color: white" %>
        </li>
      </ul>
    
    </div>
  </div>

</nav>
  <div class="uw-colour-bar">
    <div class="uw-colour-bar-1"></div>
    <div class="uw-colour-bar-2"></div>
    <div class="uw-colour-bar-3"></div>
    <div class="uw-colour-bar-4"></div>
  </div>

app/views/shared/_search_form.erb
<div class="search row collapse">
	<div class="small-2 columns">
		<span class="prefix">
			<i class="fas fa-search"></i>
		</span>
	</div>
	<div class="small-10 columns">
		<%= text_field_tag :equipment, nil, :class => 'equipsearch', :placeholder => 'Search equipment' %>
	</div>
</div>

app/views/shared/_self_serve_header.html.erb
<nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
        <li class="name">
        <h1><a href="#">MAD Equipment Booking Self-Serve</a></h1>
        </li>
        <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
        <li><%= link_to "Create Booking", selfserve_path %></li>
        <li><%= link_to "My Bookings", user_history_path %></li>
        <li>
            <%= link_to auth_logout_path, :class => 'logout-button' do %>
                <i class="fas fa-sign-out-alt"></i>
                <span>Log out <%= session[:current_username] %> </span>
            <% end %>
        </li>
        </ul>
    </section>
</nav>

app/views/shared/_self_serve_tag_list.html.erb
<select class="chosen-select" multiple>
	<% Tag.all.sort{|a,b| a.name <=> b.name}.each do |tag| %>
		<option class="ss-tag" data-tag-id='<%= tag.id.to_s %>' value='<%= tag.id.to_s %>'>
			<span class="name"><%= tag.name %></span>
		</option>
	<% end %>
</select>

app/views/shared/_sidenav.html.erb
<nav class="col-2" id="sidebar">
  <% user = User.find_by_username(session[:current_username]) %>
  <% if user.admin %>
    <div class="list-group">
      <!-- DASHBOARD -->
      <a class="list-group-item collapsed" aria-expanded="false" href="./">
        <i class="fas fa-tachometer-alt"></i>
        <span class="d-none d-lg-inline">Dashboard</span>
      </a>

      <!-- RESERVATIONS -->
      <a class="list-group-item collapsed" aria-expanded="false" href="#reservations-sidebar" data-bs-toggle="collapse">
        <i class="fas fa-calendar-alt"></i>
        <span class="d-none d-lg-inline">Reservations <i class="fa fa-caret-down"></i></span>
      </a>

      <div id="reservations-sidebar" class="collapse">
        <a class="list-group-item" href="bookings/new">Create</a>
        <a class="list-group-item" href="bookings/calendar">Calendar View</a>
        <a class="list-group-item" href="bookings">List View</a>
      </div>

      <!-- RESOURCES -->
      <a class="list-group-item collapsed" aria-expanded="false" href="#equipment-sidebar" data-bs-toggle="collapse">
        <i class="fas fa-tools"></i>
        <span class="d-none d-lg-inline">Resources <i class="fa fa-caret-down"></i></span>
      </a>

      <div id="equipment-sidebar" class="collapse">
        <a class="list-group-item" href="equipment/new">Create</a>
        <a class="list-group-item" href="equipment">List</a> 
      </div>

      <!-- USERS -->
      <a class="list-group-item collapsed" aria-expanded="false" href="#users-sidebar" data-bs-toggle="collapse">
        <i class="fas fa-users"></i>
        <span class="d-none d-lg-inline">Users <i class="fa fa-caret-down"></i></span>
      </a>

      <div id="users-sidebar" class="collapse">
        <a class="list-group-item" href="users/new">Create</a>
        <a class="list-group-item" href="users">List</a>
      </div>

      <!-- TAGS -->
      <a class="list-group-item collapsed" aria-expanded="false" href="#tags-sidebar" data-bs-toggle="collapse">
        <i class="fas fa-tags"></i>
        <span class="d-none d-lg-inline">Tags <i class="fa fa-caret-down"></i></span>
      </a>

      <div id="tags-sidebar" class="collapse">
        <a class="list-group-item" href="tags/new">Create</a>
        <a class="list-group-item" href="tags">List</a>
      </div>

      <!-- SETTINGS -->
      <a class="list-group-item collapsed" aria-expanded="false" href="collections/<%= Collection.first.id %>/edit ">
        <i class="fas fa-cog"></i>
        <span class="d-none d-lg-inline">Settings</span>
      </a>

    </div>
  <% else %>
    <a class="list-group-item collapsed" aria-expanded="false" href="bookings/">
      <i class="far fa-calendar"></i>
      <span class="d-none d-lg-inline">My Reservations</span>
    </a>
    <a class="list-group-item collapsed" aria-expanded="false" href="selfserve">
      <i class="fas fa-calendar-plus"></i>
      <span class="d-none d-lg-inline">New Reservation</span>
    </a>
  <% end %>
 


  

</nav>

app/views/shared/_tag_list.html.erb
<ul class="list tags">
	<% Tag.all.order(:name).includes(:equipment).each do |tag| %>
		<li data-tag-id='<%= tag.id.to_s %>'>
			<span class="right radius secondary label tag-count"><%= tag.equipment.length.to_s %></span><span class="name"><%= tag.name %></span>
			<% if allow_edits %>
				<i class="fas fa-edit"></i>
			<% end %>
		</li>
	<% end %>
</ul>