config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope ENV['RAILS_RELATIVE_URL_ROOT'] || '/' do
    get '/auth/create', to: 'sessions#create', as: 'auth_create'
    get '/auth/logout', to: 'sessions#destroy', as: 'auth_logout'

    resources :collections
    resources :closed_hours
    resources :open_hours
    resources :tags

    resources :settings do
      collection do
        put :update
        patch :update
      end
    end

    get '/invaliduser', to: 'pages#invaliduser', as: 'invalid_user'
    get '/selfserve', to: 'bookings#self_serve', as: 'selfserve'
    get '/selfserve_disabled', to: 'pages#selfserve_disabled', as: 'selfserve_disabled'
    get '/selfserve_success', to: 'pages#selfserve_success', as: 'selfserve_success'
    get '/selfserve_fail', to: 'pages#selfserve_fail', as: 'selfserve_fail'
    get '/approvals', to: 'bookings#approvals', as: 'approvals'
    get '/bookings/:id/reject', to: 'bookings#reject', as: 'reject', defaults: { format: :json }
    get '/bookings/:id/approve', to: 'bookings#approve', as: 'approve', defaults: { format: :json }
    post '/bookings/:id/scan', to: 'bookings#scan', as: 'scan', defaults: { format: :json }
    get '/user_history', to: 'pages#user_history', as: 'user_history'
    get '/equipment/download', to: 'equipment#download_excel'
    get '/equipment/unavailable', to: 'equipment#unavailable_time_range', defaults: { format: :json }
    get '/equipment/:id/summary_view', to: 'equipment#summary_view', as: 'equipment_summary_view'
    get '/tags/form/:tagid', to: 'tags#form', as: 'tag_form' # generate a partial to edit existing forms
    get '/users/form/:userid', to: 'users#form', as: 'user_form' # generate a partial to edit existing forms
    get '/equipment/form/:equip_id', to: 'equipment#form', as: 'equipment_form' # generate a partial to edit existing forms
    get '/bookings/:id/self_serve', to: 'bookings#self_serve', as: 'selfserve_edit'
    get '/bookings/equiprow/:equip_id', to: 'bookings#equipment_row', as: 'equiprow' # generate the partial js for a bookings row
    get '/bookings/overdue', to: 'bookings#overdue', defaults: { format: :json }
    get '/bookings/upcoming', to: 'bookings#upcoming', defaults: { format: :json }
    get '/bookings/upcoming_returns', to: 'bookings#upcoming_returns', defaults: { format: :json }
    get '/bookings/calendar', to: 'pages#calendar_new'
    get '/bookings/approvals', to: 'bookings#approvals', defaults: { format: :json }
    get '/users/validate_dept/:userid.json', to: 'users#validate_dept', defaults: { format: :json } # get whether a user is from a valid department
    get '/users/ldap/:userid.json', to: 'users#ldap', defaults: { format: :json } # get LDAP details for a user
    get '/users/ldap_user/:username.json', to: 'users#valid_ldap_user', defaults: { format: :json } # determine if a username exists in LDAP
    get '/users/:column.json', to: 'users#column', defaults: { format: :json }, constraints: ->(request) { User.column_names.include?(request.params[:column]) }
    get '/users/ldap_search/', to: 'users#ldap_search', defaults: { format: :json }
    get '/equipment/bytag/', to: 'equipment#tags', as: 'bytag'
    get '/equipment/:column.json', to: 'equipment#column', defaults: { format: :json }, constraints: ->(request) { Equipment.column_names.include?(request.params[:column]) }
    get '/hours_by_date', to: 'settings#hours_by_date', as: 'hours_by_date', defaults: { format: :json }
    get '/events/calendar', to: 'events#calendar', defaults: { format: :json }
    get '/equipment/:id/future_events', to: 'equipment#future_events', defaults: { format: :json }

    resources :equipment
    resources :users
    resources :bookings
    resources :events

    root to: 'pages#home2'
  end
end

app/models/open_hour.rb
# frozen_string_literal: true

# OpenHour represents a schedule during which the service is open.
# It consists of a boolean value for each day of the week, indicating
# if the service is open on that day.
# It also has a start and end time, which are the hours that the service is
# open during the days defined as open.
# Lastly, it has a valid from/until range. These are the dates during which the
# schedule is valid.
class OpenHour < ActiveRecord::Base
  validate :correct_times

  # given a date, return an array of open times with this format:
  # [[start,end],[start,end],...,[start,end]]
  def self.open_times_from_date(test_date)
    open_times = []

    OpenHour.all.each do |oh|
      if test_date.between?(oh.valid_from, oh.valid_until) &&
         oh.send(Date::DAYNAMES[test_date.wday].downcase)
        open_times.push([oh.start_time, oh.end_time])
      end
    end

    open_times
  end

  private

  def correct_times
    # Is the start date before the end date
    valid_dates = valid_from <= valid_until

    # is the start time before the end time?
    valid_times = start_time < end_time

    valid = valid_times && valid_dates
    return if valid

    # If the times aren't valid, return the error
    errors.add(
      :open_hour,
      'cannot be saved: Start time must come before end time'
    )
  end
end

app/controllers/open_hours_controller.rb
# frozen_string_literal: true

class OpenHoursController < ApplicationController
  before_action :set_open_hour, only: %i[show edit update destroy]

  before_action :authenticate
  before_action :authenticate_admin

  # GET /open_hours
  def index
    @open_hours = OpenHour.all
  end

  # GET /open_hours/1
  def show; end

  # GET /open_hours/new
  def new
    @open_hour = OpenHour.new
  end

  # GET /open_hours/1/edit
  def edit; end

  # POST /open_hours
  def create
    @open_hour = OpenHour.new(open_hour_params)
    # st = Time.strptime(open_hour_params[:start_time], "%k:%M")
    # et = Time.strptime(open_hour_params[:end_time], "%k:%M")

    # @open_hour.start_time = convert_to_utc(st.hour, st.min)
    # @open_hour.end_time = convert_to_utc(et.hour, et.min)
    @open_hour.start_time = Time.zone.parse(open_hour_params[:start_time]).utc
    @open_hour.end_time = Time.zone.parse(open_hour_params[:end_time]).utc

    if @open_hour.save
      redirect_to open_hours_path, notice: 'Open hour was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /open_hours/1
  def update
    # st = Time.strptime(open_hour_params[:start_time], "%k:%M")
    # et = Time.strptime(open_hour_params[:end_time], "%k:%M")
    
    @open_hour.attributes = open_hour_params
    # @open_hour.start_time = convert_to_utc(st.hour, st.min)
    # @open_hour.end_time = convert_to_utc(et.hour, et.min)
    @open_hour.start_time = Time.zone.parse(open_hour_params[:start_time]).utc
    @open_hour.end_time = Time.zone.parse(open_hour_params[:end_time]).utc

    if @open_hour.save
      redirect_to open_hours_path, notice: 'Open hour was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /open_hours/1
  def destroy
    @open_hour.destroy
    redirect_to open_hours_url, notice: 'Open hour was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_open_hour
    @open_hour = OpenHour.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def open_hour_params
    params.require(:open_hour).permit(:valid_from, :valid_until, :start_time, :end_time, :sunday, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday)
  end

  def convert_to_utc(hours, minutes)
    t = Time.new(2000, 1, 1, hours, minutes, 0)
    t.utc
  end
end

app/helpers/open_hours_helper.rb
# frozen_string_literal: true

module OpenHoursHelper
end

app/views/open_hours/_form.html.erb
<%= vite_client_tag %>
<%= vite_javascript_tag "open_hour" %>

<div id="open_hour_form">
  <%= form_for(@open_hour) do |f| %>
    <% if @open_hour.errors.any? %>
      <div id="error_explanation">
        <h3><%= pluralize(@open_hour.errors.count, "error") %> prohibited this open_hour from being saved:</h3>

        <ul>
        <% @open_hour.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-row mb-3">
      <div class="col-6">
        <div class="card">
          <div class="card-header">Dates/Times</div>
          <div class="card-body">
            <div id="open_hour_dates_times">

              <%
                vf_val = @open_hour.valid_from.nil? ? DateTime.now : @open_hour.valid_from.iso8601
              %>
              <%= f.label :valid_from %>

              <input type="date" name="open_hour[valid_from]" value=<%= vf_val %>>
              <br />

              <%
                vu_val = @open_hour.valid_until.nil? ? DateTime.now : @open_hour.valid_until.iso8601
              %>
              <%= f.label :valid_until %>
              <input type="date" name="open_hour[valid_until]" value=<%= vu_val %>>
              <br />

              <%
                st_value = @open_hour.start_time.nil? ? Time.current.strftime("%H:%M") : @open_hour.start_time.in_time_zone.strftime("%H:%M")
              %>
              <%= f.label :start_time %>
              <input type="time" name="open_hour[start_time]" value=<%= st_value %>>
              <br />


              <%
                et_value = @open_hour.end_time.nil? ? Time.current.strftime("%H:%M") : @open_hour.end_time.in_time_zone.strftime("%H:%M")
              %>
              <%= f.label :end_time %>
              <input type="time" name="open_hour[end_time]" value=<%= et_value %>>
              <br />

            </div>
            
              
          </div>
        </div>
      </div>
      <div class="col-6">
        <div class="card">
          <div class="card-header">Days</div>
          <div class="card-body">
            <div class="days">
              <div class="field">
                <%= f.check_box :sunday %>
                <%= f.label :sunday %>
              </div>
              <div class="field">
                <%= f.check_box :monday %>
                <%= f.label :monday %>
              </div>
              <div class="field">
                <%= f.check_box :tuesday %>
                <%= f.label :tuesday %>
              </div>
              <div class="field">
                <%= f.check_box :wednesday %>
                <%= f.label :wednesday %>
              </div>
              <div class="field">
                <%= f.check_box :thursday %>
                <%= f.label :thursday %>
              </div>
              <div class="field">
                <%= f.check_box :friday %>
                <%= f.label :friday %>
              </div>
              <div class="field">
                <%= f.check_box :saturday %>
                <%= f.label :saturday %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    
    
    <div class="form-row">
      <div class="col">
        <% if @open_hour.new_record? %>
          <%= f.submit "Create new open hour range", { class: "btn btn-primary mr-2" } %>
          <%= link_to 'Cancel', open_hours_path, method: :get, class: "btn btn-secondary" %>
        <% else %>
          <%= f.submit "Edit open hour range", { class: "btn btn-primary mr-2" } %>
          <%= link_to 'Cancel', @open_hour, method: :get, class: "btn btn-secondary" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/open_hours/edit.html.erb
<main id="edit_open_hour">
  <h2>Editing Opening Hour Range</h2>

  <%= render 'form' %>

</div>

app/views/open_hours/index.html.erb
<main id="open_hour_list">
  <h2>Opening Hours</h2>

  <div class="card">
    <div class="card-header">Instructions</div>
    <div class="card-body">
      Bookings can be created whenever:
      <ul>
        <li>Start and end times for the booking fall on a day/time
            within one of the opening hour ranges below</li>
        <li>Start and end times for the booking do not fall in a 
            <%= link_to 'closed range', closed_hours_path %></li>
      </ul>
    </div>
  </div>
  


  <table class="table">
    <thead>
      <tr>
        <th>Valid from</th>
        <th>Valid until</th>
        <th>Start time</th>
        <th>End time</th>
        <th>Sunday</th>
        <th>Monday</th>
        <th>Tuesday</th>
        <th>Wednesday</th>
        <th>Thursday</th>
        <th>Friday</th>
        <th>Saturday</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @open_hours.each do |open_hour| %>
        <tr>
          <td><%= open_hour.valid_from %></td>
          <td><%= open_hour.valid_until %></td>
          <td><%= open_hour.start_time.in_time_zone.strftime("%l:%M %P") %></td>
          <td><%= open_hour.end_time.in_time_zone.strftime("%l:%M %P") %></td>
          <td><%= open_hour.sunday %></td>
          <td><%= open_hour.monday %></td>
          <td><%= open_hour.tuesday %></td>
          <td><%= open_hour.wednesday %></td>
          <td><%= open_hour.thursday %></td>
          <td><%= open_hour.friday %></td>
          <td><%= open_hour.saturday %></td>
          <td><%= link_to 'Edit', edit_open_hour_path(open_hour) %></td>
          <td><%= button_to 'Delete', open_hour, {method: :delete, onclick: "return confirm('Are you sure?')"} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="form-row">
    <%= link_to new_open_hour_path, { class: "btn btn-primary mr-3" } do %>
      <i class="fas fa-plus"></i> 
      Define New Opening Hour Range
    <% end %>
    <%= link_to edit_collection_path(Collection.first), { class: "btn btn-secondary mr-3" } do %>
      <i class="fas fa-cog"></i> 
      Back to Settings
    <% end %>
    <%= link_to root_path, { class: "btn btn-secondary" } do %>
      <i class="fas fa-calendar-alt"></i> 
      Back to Calendar
    <% end %>
  </div>
  
</div>

app/views/open_hours/new.html.erb
<main id="new_open_hour">
  <h2>New Opening Hour Range</h2>

  <%= render 'form' %>

</div>

app/views/open_hours/show.html.erb
<div class="form-row mt-3">
      <div class="col-6">
        <div class="card">
          <div class="card-header">Dates/Times</div>
          <div class="card-body">
            <div>
              <strong>Valid from:</strong>
              <%= @open_hour.valid_from %><br />
              <strong>Valid until:</strong>
              <%= @open_hour.valid_until %><br />
              <strong>Start Time:</strong>
              <%= @open_hour.start_time.localtime.strftime('%l:%M %p') %><br />
              <strong>End Time:</strong>
              <%= @open_hour.end_time.localtime.strftime('%l:%M %p') %><br />
            </div>
          </div>
        </div>
      </div>
      <div class="col-6">
        <div class="card">
          <div class="card-header">Days</div>
          <div class="card-body">
            <div>
              <strong>Sunday:</strong>
              <%= @open_hour.sunday %><br />
              <strong>Monday:</strong>
              <%= @open_hour.monday %><br />
              <strong>Tuesday:</strong>
              <%= @open_hour.tuesday %><br />
              <strong>Wednesday:</strong>
              <%= @open_hour.wednesday %><br />
              <strong>Thursday:</strong>
              <%= @open_hour.thursday %><br />
              <strong>Friday:</strong>
              <%= @open_hour.friday %><br />
              <strong>Saturday:</strong>
              <%= @open_hour.saturday %><br />
            </div>
          </div>
        </div>
      </div>
    </div>
<%= link_to 'Edit', edit_open_hour_path(@open_hour) %> |
<%= link_to 'Back', open_hours_path %>