config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope ENV['RAILS_RELATIVE_URL_ROOT'] || '/' do
    get '/auth/create', to: 'sessions#create', as: 'auth_create'
    get '/auth/logout', to: 'sessions#destroy', as: 'auth_logout'

    resources :collections
    resources :closed_hours
    resources :open_hours
    resources :tags

    resources :settings do
      collection do
        put :update
        patch :update
      end
    end

    get '/invaliduser', to: 'pages#invaliduser', as: 'invalid_user'
    get '/selfserve', to: 'bookings#self_serve', as: 'selfserve'
    get '/selfserve_disabled', to: 'pages#selfserve_disabled', as: 'selfserve_disabled'
    get '/selfserve_success', to: 'pages#selfserve_success', as: 'selfserve_success'
    get '/selfserve_fail', to: 'pages#selfserve_fail', as: 'selfserve_fail'
    get '/approvals', to: 'bookings#approvals', as: 'approvals'
    get '/bookings/:id/reject', to: 'bookings#reject', as: 'reject', defaults: { format: :json }
    get '/bookings/:id/approve', to: 'bookings#approve', as: 'approve', defaults: { format: :json }
    post '/bookings/:id/scan', to: 'bookings#scan', as: 'scan', defaults: { format: :json }
    get '/user_history', to: 'pages#user_history', as: 'user_history'
    get '/equipment/download', to: 'equipment#download_excel'
    get '/equipment/unavailable', to: 'equipment#unavailable_time_range', defaults: { format: :json }
    get '/equipment/:id/summary_view', to: 'equipment#summary_view', as: 'equipment_summary_view'
    get '/tags/form/:tagid', to: 'tags#form', as: 'tag_form' # generate a partial to edit existing forms
    get '/users/form/:userid', to: 'users#form', as: 'user_form' # generate a partial to edit existing forms
    get '/equipment/form/:equip_id', to: 'equipment#form', as: 'equipment_form' # generate a partial to edit existing forms
    get '/bookings/:id/self_serve', to: 'bookings#self_serve', as: 'selfserve_edit'
    get '/bookings/equiprow/:equip_id', to: 'bookings#equipment_row', as: 'equiprow' # generate the partial js for a bookings row
    get '/bookings/overdue', to: 'bookings#overdue', defaults: { format: :json }
    get '/bookings/upcoming', to: 'bookings#upcoming', defaults: { format: :json }
    get '/bookings/upcoming_returns', to: 'bookings#upcoming_returns', defaults: { format: :json }
    get '/bookings/calendar', to: 'pages#calendar_new'
    get '/bookings/approvals', to: 'bookings#approvals', defaults: { format: :json }
    get '/users/validate_dept/:userid.json', to: 'users#validate_dept', defaults: { format: :json } # get whether a user is from a valid department
    get '/users/ldap/:userid.json', to: 'users#ldap', defaults: { format: :json } # get LDAP details for a user
    get '/users/ldap_user/:username.json', to: 'users#valid_ldap_user', defaults: { format: :json } # determine if a username exists in LDAP
    get '/users/:column.json', to: 'users#column', defaults: { format: :json }, constraints: ->(request) { User.column_names.include?(request.params[:column]) }
    get '/users/ldap_search/', to: 'users#ldap_search', defaults: { format: :json }
    get '/equipment/bytag/', to: 'equipment#tags', as: 'bytag'
    get '/equipment/:column.json', to: 'equipment#column', defaults: { format: :json }, constraints: ->(request) { Equipment.column_names.include?(request.params[:column]) }
    get '/hours_by_date', to: 'settings#hours_by_date', as: 'hours_by_date', defaults: { format: :json }
    get '/events/calendar', to: 'events#calendar', defaults: { format: :json }
    get '/equipment/:id/future_events', to: 'equipment#future_events', defaults: { format: :json }

    resources :equipment
    resources :users
    resources :bookings
    resources :events

    root to: 'pages#home2'
  end
end

app/models/closed_hour.rb
# frozen_string_literal: true

# ClosedHour represents a range of time when the service is closed.
# It consists of a start_date_time and end_date_time. These override
# OpenHour definitions.
class ClosedHour < ActiveRecord::Base
  validates :closed_start, presence: true
  validates :closed_end, presence: true
  validate :correct_times

  # given a date, return an array of closed times with this format:
  # [[start,end],[start,end],...,[start,end]]
  def self.closed_times_from_date(test_date)
    closed_times = []
    ClosedHour.all.each do |ch|
      next unless test_date.to_date.between?(
        ch.closed_start.to_date,
        ch.closed_end.to_date
      )

      closed_times.push([ch.closed_start, ch.closed_end])
    end
    closed_times
  end

  private

  def correct_times
    valid = false
    valid = closed_start < closed_end if !closed_start.nil? && !closed_end.nil?
    return if valid

    # If the times are not valid, add an error
    errors.add(
      :closed_hour,
      'cannot be saved: Start time must come before end time'
    )
  end
end

app/controllers/closed_hours_controller.rb
# frozen_string_literal: true

class ClosedHoursController < ApplicationController
  before_action :set_closed_hour, only: %i[show edit update destroy]

  before_action :authenticate
  before_action :authenticate_admin

  # GET /closed_hours
  def index
    @closed_hours = ClosedHour.all
  end

  # GET /closed_hours/1
  def show; end

  # GET /closed_hours/new
  def new
    @closed_hour = ClosedHour.new
  end

  # GET /closed_hours/1/edit
  def edit; end

  # POST /closed_hours
  def create
    # @closed_hour = ClosedHour.new(closed_hour_params)
    closed_hour_start = params[:closed_hour_start_date] + 'T' + params[:closed_hour_start_time]
    closed_hour_end = params[:closed_hour_end_date] + 'T' + params[:closed_hour_end_time]
    
    @closed_hour = ClosedHour.new(
      closed_start: closed_hour_start,
      closed_end: closed_hour_end
    )
    if @closed_hour.save
      redirect_to closed_hours_path, notice: 'Closed hour was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /closed_hours/1
  def update
    if @closed_hour.update(closed_hour_params)
      redirect_to closed_hours_path, notice: 'Closed hour was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /closed_hours/1
  def destroy
    @closed_hour.destroy
    redirect_to closed_hours_url, notice: 'Closed hour was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_closed_hour
    @closed_hour = ClosedHour.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def closed_hour_params
    params.require(:closed_hour).permit(:closed_start, :closed_end)
  end
end

app/helpers/closed_hours_helper.rb
# frozen_string_literal: true

module ClosedHoursHelper
end

app/views/closed_hours/_form.html.erb
<%= vite_client_tag %>
<%= vite_javascript_tag "closed_hour" %>

<div id="closed_hour_form">
  <%= form_for(@closed_hour) do |f| %>
    <% if @closed_hour.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@closed_hour.errors.count, "error") %> prohibited this closed_hour from being saved:</h2>

        <ul>
        <% @closed_hour.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-row mb-3">
      <div class="col">
        <div class="card">
          <div class="card-header">Dates/Times</div>
          <div class="card-body">
            <div id="closed_hour_dates_times">
              <%
                csd_val = @closed_hour.closed_start.nil? ? DateTime.now.strftime("%Y-%m-%d") : @closed_hour.closed_start.strftime("%Y-%m-%d")
                cst_val = @closed_hour.closed_start.nil? ? DateTime.now.strftime("%H:%M") : @closed_hour.closed_start.strftime("%H:%M")
                ced_val = @closed_hour.closed_end.nil? ? DateTime.now.strftime("%Y-%m-%d") : @closed_hour.closed_end.strftime("%Y-%m-%d")
                cet_val = @closed_hour.closed_end.nil? ? DateTime.now.strftime("%H:%M") : @closed_hour.closed_end.strftime("%H:%M")
              %>
              <%= f.label 'Start of range' %><br>
              <input type="date" name="closed_hour_start_date" value=<%= csd_val %>>
              <input type="time" name="closed_hour_start_time" value=<%= cst_val %>><br />
              <%= f.label 'End of range' %><br>
              <input type="date" name="closed_hour_end_date" value=<%= ced_val %>>
              <input type="time" name="closed_hour_end_time" value=<%= cet_val %>>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/closed_hours/edit.html.erb
<div class='closed-hour-content'>
  <h1>Closed Hours</h1>

  <%= render 'form' %>

  <%= link_to 'Back', closed_hours_path %>
</div>

app/views/closed_hours/index.html.erb
<main id="closed_hour_list">
  <h2>Closed Hours</h2>
   <div class="card">
    <div class="card-header">Instructions</div>
    <div class="card-body">
      Bookings can be created whenever:
      <ul>
        <li>Start and end times for the booking fall on a day/time
            within one of the <%= link_to 'open ranges', open_hours_path %></li>
        <li>Start and end times for the booking do not fall in a 
            closed range below</li>
      </ul>
    </div>
  </div>



  <table class="table">
    <thead>
      <tr>
        <th>Closed start</th>
        <th>Closed end</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @closed_hours.each do |closed_hour| %>
        <tr>
          <td><%= closed_hour.closed_start.localtime.strftime("%F %I:%M %p") %></td>
          <td><%= closed_hour.closed_end.localtime.strftime("%F %I:%M %p") %></td>
          <td><%= button_to 'Edit', edit_closed_hour_path(closed_hour), method: :get %></td>
          <td><%= button_to 'Delete', closed_hour, {method: :delete, onclick: "return confirm('Are you sure?')"} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <div class="form-row">
    <%= link_to new_closed_hour_path, { class: "btn btn-primary mr-3" } do %>
      <i class="fas fa-plus"></i> 
      Define New Closed Hour Range
    <% end %>
    <%= link_to edit_collection_path(Collection.first), { class: "btn btn-secondary mr-3" } do %>
      <i class="fas fa-cog"></i> 
      Back to Settings
    <% end %>
    <%= link_to root_path, { class: "btn btn-secondary" } do %>
      <i class="fas fa-calendar-alt"></i> 
      Back to Calendar
    <% end %>
  </div>

</div>

app/views/closed_hours/new.html.erb
<div class='closed-hour-content'>
  <h1>New Closed Hours</h1>

  <%= render 'form' %>

  <%= link_to 'Back', closed_hours_path %>
</div>

app/views/closed_hours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Closed start:</strong>
  <%= @closed_hour.closed_start %>
</p>

<p>
  <strong>Closed end:</strong>
  <%= @closed_hour.closed_end %>
</p>

<%= link_to 'Edit', edit_closed_hour_path(@closed_hour) %> |
<%= link_to 'Back', closed_hours_path %>